### ISSUE TITLE
Support for iPhone 13 Pro

### ISSUE THREAD

**Issue by trevorwatkins1129** [EthanArbuckle/carplay-cast#84] opened 2024-02-25 18:55 UTC
Error saying it only supports arm, not arm64.

**Comment by EthanArbuckle** [comment] 2024-04-01 13:18
yes, the current version doesn't support newer jailbreaks. I'm going to consider this issue "ios 15+ support" and close it as a dupe of https://github.com/EthanArbuckle/carplay-cast/issues/77

iOS 15 support is in progress

**Closed as completed by EthanArbuckle** 2024-04-01 13:18 UTC
